# Generated by Django 4.1 on 2022-08-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
